var windowHeight = $(window).height() ; // This function gets us the height of the element specified....note that window represents the whole page
var menuBarHeight = $("#menuBar").height() ;
var codeContainerHeight = windowHeight-menuBarHeight ;
$(".codeContainer").height(codeContainerHeight+"px") ; // set the height of each code container

$(".toggle").click(function(){ // Here we want to check whether the toggle class selected or not and if it was selected we want to deselect
$(this).toggleClass("selected") ;

var activeDiv = $(this).html() ;
$("#"+activeDiv+"Container").toggle() ;

var showingDivs = $(".codeContainer").filter(function(){ //this function(filter) acts as a loop it loops through all contents of class codeContainer
	return($(this).css("display")!="none") ; 				// and the (.length) on the end sets it to loop through all elements of it
}).length;

var divWidth = 100/showingDivs ; // now showingDivs is the number of shown divs, so each of them will have width = 100/showingDivs %
$(".codeContainer").width(divWidth+"%") ;
});

$("#runButton").click(function(){
$("iframe").contents().find("html").html('<style>'+$("#cssCode").val()+'</style>'+$("#htmlCode").val()) ;

// contents -> searches the iframe
// find -> finds the tag named "html"
// .html -> sets the HTML of that tag to what in bracket
document.getElementById('resultFrame').contentWindow.eval($("#jsCode").val()) ;
/* note that eval isn't a safe function to use...if we gonna upload this site to a server or so we better remove it cuz it will allow the 
users to alter the javascript content of our site and access its files and content which is extremely dangerous*/
// The contentWindow property returns the Window object generated by an iframe element
// The eval() function evaluates or executes an argument
//If the argument is an expression, eval() evaluates the expression. If the argument is one or more JavaScript statements, eval() executes the statements
});